apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-app-env
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: example-app-env
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: example-app-config # Vault secret 하나 = 앱 하나의 env JSON
